#include <dbi>

Database g_db_weapons = null;

static const char sqlite_schema_tf2itemplugin_weapons[512] =
    "CREATE TABLE IF NOT EXISTS tf2itemplugin_weapons (" ...
        "weapon_id INTEGER PRIMARY KEY AUTOINCREMENT," ...
        "weapon_name TEXT NOT NULL," ...
        "weapon_class TEXT NOT NULL," ...
        "weapon_slot TEXT NOT NULL," ...
        "weapon_slot_position INTEGER NOT NULL," ...
        "weapon_enabled INTEGER NOT NULL" ...
    ");";