#include <dbi>

Database g_db_weapons = null;

static const char sqlite_schema_tf2itemplugin_weapons[512] =
    "CREATE TABLE IF NOT EXISTS tf2itemplugin_weapons (" ...
        "client INTEGER NOT NULL," ...
        "class INTEGER NOT NULL," ...
        "slotId INTEGER NOT NULL," ...
        "isActiveOverride INTEGER NOT NULL," ...
        "weaponDefIndex INTEGER NOT NULL," ...
        "stockWeaponDefIndex INTEGER NOT NULL," ...
        "quality INTEGER NOT NULL," ...
        "level INTEGER NOT NULL," ...
        "isAustralium INTEGER NOT NULL," ...
        "isFestive INTEGER NOT NULL," ...
        "warPaintId INTEGER NOT NULL," ...
        "warPaintWear REAL NOT NULL," ...
        "unusualEffectId INTEGER NOT NULL," ...
        "halloweenSpellIsActive INTEGER NOT NULL," ...
        "halloweenSpellSpells INTEGER NOT NULL," ...
        "killstreakIsActive INTEGER NOT NULL," ...
        "killstreakTier INTEGER NOT NULL," ...
        "killstreakSheen INTEGER NOT NULL," ...
        "killstreakKillstreaker INTEGER NOT NULL," ...
        "PRIMARY KEY (client, class, slotId)" ...
    ");";


